---
name: Net-Whois-Gateway-Server
version: 0.09
author:
  - 'Sergey Kotenko <graykot@gmail.com>'
abstract: whois gateway
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Net::Ifconfig::Wrapper: 0
  POE: 0
  POE::Component::Client::Whois::Smart: 0.11
  POE::Component::Server::TCP: 0
  POE::Filter::Reference: 0
  Proc::Daemon: 0
  Proc::PID::File: 0
configure_requires:
  Module::Build: 0.35
provides:
  Net::Whois::Gateway::Server:
    file: lib/Net/Whois/Gateway/Server.pm
    version: 0.09
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
